### ISSUE TITLE
error when i launch singleswap

### ISSUE THREAD

**Issue by kalistar49** [harisreedhar/SimSwap-GUI#1]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\danie\anaconda3\envs\simswap\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\danie\anaconda3\envs\simswap\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "simswap_gui.py", line 1188, in wrapper
    self.widgets_state(state='disabled')
  File "simswap_gui.py", line 1369, in widgets_state
    set_child_state(self.frame_1)
  File "simswap_gui.py", line 1368, in set_child_state
    set_child_state(child)
  File "simswap_gui.py", line 1366, in set_child_state
    child.configure(state=state)
  File "C:\Users\danie\anaconda3\envs\simswap\lib\tkinter\ttk.py", line 1091, in configure
    Widget.configure(self, **kw)
  File "C:\Users\danie\anaconda3\envs\simswap\lib\tkinter\__init__.py", line 1485, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\danie\anaconda3\envs\simswap\lib\tkinter\__init__.py", line 1476, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-state"

**Comment by harisreedhar** [comment]
@kalistar49  I can't reproduce this error. Can you guide me to reproduce it?

**Comment by kalistar49** [comment]
this happens when I click on one of the 3 swap buttons

by analyzing the error with chatgpt I found that it would come from this part of the code:

`    def widgets_state(self, state='disable'):
        def set_child_state(widget):
            for child in widget.winfo_children():
                wtype = child.winfo_class()
                if wtype not in ('TFrame','TLabelframe', 'Frame', 'Labelframe', 'Menu', 'TLabel'):
                    child.configure(state=state)
                else:
                    set_child_state(child)
        set_child_state(self.frame_1)
        set_child_state(self.frame_2)
        set_child_state(self.frame_3)
        set_child_state(self.frame_4)`

Chat gpt offered me this fix.

`if "state" in child.keys() and wtype not in ('TFrame','TLabelframe', 'Frame', 'Labelframe', 'Menu', 'TLabel'):
                    child.configure(state=state)`

but i don't think this is the solution because now i have this error


------------ Options -------------
Arc_path: models/BEST_checkpoint.tar
aspect_ratio: 1.0
batchSize: 8
checkpoints_dir: ./checkpoints
cluster_path: features_clustered_010.npy
crop_size: 224
data_type: 32
dataroot: ./datasets/cityscapes/
display_winsize: 512
engine: None
export_onnx: None
feat_num: 3
fineSize: 512
fp16: False
gpu_ids: [0]
how_many: 50
id_thres: 0.03
image_size: 224
input_nc: 3
instance_feat: False
isTrain: False
label_feat: False
label_nc: 0
latent_size: 512
loadSize: 1024
load_features: False
local_rank: 0
max_dataset_size: inf
model: pix2pixHD
multisepcific_dir: ./demo_file/multispecific
nThreads: 2
n_blocks_global: 6
n_blocks_local: 3
n_clusters: 10
n_downsample_E: 4
n_downsample_global: 3
n_local_enhancers: 1
name: people
nef: 16
netG: global
ngf: 64
niter_fix_global: 0
no_flip: False
no_instance: False
no_simswaplogo: False
norm: batch
norm_G: spectralspadesyncbatch3x3
ntest: inf
onnx: None
output_nc: 3
output_path: ./output/
phase: test
pic_a_path: ./crop_224/gdg.jpg
pic_b_path: ./crop_224/zrf.jpg
pic_specific_path: ./crop_224/zrf.jpg
resize_or_crop: scale_width
results_dir: ./results/
semantic_nc: 3
serial_batches: False
temp_path: ./temp_results
tf_log: False
use_dropout: False
use_encoded_image: False
use_mask: False
verbose: False
video_path: ./demo_file/multi_people_1080p.mp4
which_epoch: latest
-------------- End ----------------
input mean and std: 127.5 127.5
find model: ./insightface_func/models\antelope\glintr100.onnx recognition
find model: ./insightface_func/models\antelope\scrfd_10g_bnkps.onnx detection
set det-size: (640, 640)
'NoneType' object is not iterable

I specify that simswap works very well in command line

**Comment by harisreedhar** [comment]
1.You can ignore that part of code by replacing ``child.configure(state=state)`` with ``pass``.
2.``NoneType' object is not iterable``  This error usually occurs when source or target is missing or detection threshold is high. Lower detection threshold and try again

**Comment by kalistar49** [comment]
thx that's work at 0.2 detection threshold.
what is this parameter for? does it affect the quality?

**Comment by harisreedhar** [comment]
Lowering threshold value increases target detection accuracy.
