### ISSUE TITLE
Error while execute

### ISSUE THREAD

**Issue by ShmuelRonen** [harisreedhar/SimSwap-GUI#2]
Hello... Need help

I have a working simswap installation.
I installed your GUI according to the instructions including installing tkinterdnd2.

After I enter all the parameters of source\target and click on Swap Single I got everytime this error: <_tkinter.TclError: unknown option "-state">

_____________
(base) C:\Users\derec>conda activate P:\FaceSwapSuite\fss

(P:\FaceSwapSuite\fss) C:\Users\derec>cd C:\SimSwap\Simswap\SimSwap-main

(P:\FaceSwapSuite\fss) C:\SimSwap\Simswap\SimSwap-main>python simswap_gui.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "P:\FaceSwapSuite\fss\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "P:\FaceSwapSuite\fss\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "simswap_gui.py", line 1188, in wrapper
    self.widgets_state(state='disabled')
  File "simswap_gui.py", line 1369, in widgets_state
    set_child_state(self.frame_1)
  File "simswap_gui.py", line 1368, in set_child_state
    set_child_state(child)
  File "simswap_gui.py", line 1366, in set_child_state
    child.configure(state=state)
  File "P:\FaceSwapSuite\fss\lib\tkinter\ttk.py", line 1091, in configure
    Widget.configure(self, **kw)
  File "P:\FaceSwapSuite\fss\lib\tkinter\__init__.py", line 1485, in configure
    return self._configure('configure', cnf, kw)
  File "P:\FaceSwapSuite\fss\lib\tkinter\__init__.py", line 1476, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-state"

**Comment by ShmuelRonen** [comment]
![Screenshot 2023-06-23 175546](https://github.com/harisreedhar/SimSwap-GUI/assets/80190186/1282363a-4686-4689-96c8-6d6d7c2552a2)

**Comment by harisreedhar** [comment]
I can't reproduce the error. But you can skip those errors by removing this function contents
https://github.com/harisreedhar/SimSwap-GUI/blob/08dd982a79fcaa4f9ad7f784750cd887e2293976/simswap_gui.py#L1361
to this
```
def widgets_state(self, state='disable'):
    pass
```

**Comment by ShmuelRonen** [comment]
Thanks!!  now it working.

Can you explain to me what is Target image. It for working with 2 images, like source/terget to  swap facess?

and if you can about the difference between Swap multiply and Swap all.

**Comment by harisreedhar** [comment]
Target image is the specific/particular face you want to swap in the video.
For example, if the video contains 2 people A and B. You want to swap only A's face you can put A as target image.

**Comment by ShmuelRonen** [comment]
Thanks!!
