### ISSUE TITLE
can u update installation instruction of swapmukham

### ISSUE THREAD

**Issue by mukeshsnp12** [harisreedhar/SimSwap-GUI#4]
@harisreedhar 
Hi
Can you update installation instruction of new swapmukham?
I tried to install, but not working

**Comment by mukeshsnp12** [comment]
@harisreedhar 
 File "E:\Swap-Mukham\app.py", line 410, in <module>
    ui.queue(concurrency_count=2, api_open = False)
  File "C:\Users\Mukesh\.conda\envs\swapmukham\lib\site-packages\gradio\blocks.py", line 1676, in queue
    raise DeprecationWarning(
DeprecationWarning: concurrency_count has been deprecated. Set the concurrency_limit directly on event listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). If necessary, the total number of workers can be configured via `max_threads` in launch().

**Comment by harisreedhar** [comment]
Use gradio 3.50.2
